=== bolt12/DAW1819/tpc2/pn.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pn (cabecalho,descritivo,contexto,decisoes) >

<!ELEMENT cabecalho (estado,pai,codigo,titulo) >

<!ELEMENT estado (#PCDATA) >

<!ELEMENT pai (url,nome) >
<!ELEMENT url (#PCDATA) >
<!ELEMENT nome (#PCDATA) >

<!ELEMENT codigo (#PCDATA) >
<!ELEMENT titulo (#PCDATA) >

<!ELEMENT descritivo (descricao,naplicacao,eaplicacao,nexclusao,termos) >

<!ELEMENT descricao (#PCDATA) >

<!ELEMENT naplicacao (nota)+ >
<!ELEMENT nota (#PCDATA) >

<!ELEMENT eaplicacao (exemplo)+ >
<!ELEMENT exemplo (#PCDATA) >

<!ELEMENT nexclusao (exclusao)+ >
<!ELEMENT exclusao (nota, url, nome) >

<!ELEMENT termos (termo)+ >
<!ELEMENT termo (#PCDATA) >

<!ELEMENT contexto (tipo,transversal,donos,tintervencao,relacionados,legislacao) >
<!ELEMENT tipo (#PCDATA) >
<!ELEMENT transversal (#PCDATA) >

<!ELEMENT donos (dono)+ >
<!ELEMENT dono (sigla, nome) >
<!ELEMENT sigla (#PCDATA) >

<!ELEMENT tintervencao (comunicar,iniciar) >
<!ELEMENT comunicar (participante)+ >
<!ELEMENT iniciar (participante)+ >
<!ELEMENT participante (sigla, nome) >

<!ELEMENT relacionados (antecessor,sintese,sintetizado,sucessor,suplemento,suplementop) >
<!ELEMENT antecessor (processo)+ >
<!ELEMENT sintese (processo)+ >
<!ELEMENT sintetizado (processo)+ >
<!ELEMENT sucessor (processo)+ >
<!ELEMENT suplemento (processo)+ >
<!ELEMENT suplementop (processo)+ >
<!ELEMENT processo (url,nome) >

<!ELEMENT legislacao (legis)+ >
<!ELEMENT legis (tipo,artigo,definicao) >
<!ELEMENT artigo (#PCDATA) >
<!ELEMENT definicao (#PCDATA) >

<!ELEMENT decisoes (prazoca,destinof) >
<!ELEMENT prazoca (prazo,forma,justificacao) >
<!ELEMENT prazo (#PCDATA) >
<!ELEMENT forma (#PCDATA) >
<!ELEMENT justificacao (para)+ >
<!ELEMENT para (titulo,p) >
<!ELEMENT p (#PCDATA|link)* >
<!ELEMENT link (url,nome) >

<!ELEMENT destinof (destino,justificacao) >
<!ELEMENT destino (#PCDATA) >

=== bolt12/DAW1819/tpc2/pn_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pn SYSTEM "pn.dtd">
<pn>
    <cabecalho>
        <estado></estado>
        <pai>
            <url></url>
            <nome></nome>
        </pai>
        <codigo></codigo>
        <titulo></titulo>
    </cabecalho>
    <descritivo>
        <descricao></descricao>
        <naplicacao>
            <nota></nota>
        </naplicacao>
        <eaplicacao>
            <exemplo></exemplo>
        </eaplicacao>
        <nexclusao>
            <exclusao>
                <nota></nota>
                <url></url>
                <nome></nome>
            </exclusao>
        </nexclusao>
        <termos>
            <termo></termo>
        </termos>
    </descritivo>
    <contexto>
        <tipo></tipo>
        <transversal></transversal>
        <donos>
            <dono>
                <sigla></sigla>
                <nome></nome>
            </dono>
        </donos>
        <tintervencao>
            <comunicar>
                <participante>
                    <sigla></sigla>
                    <nome></nome>
                </participante>
            </comunicar>
            <iniciar>
                <participante>
                    <sigla></sigla>
                    <nome></nome>
                </participante>
            </iniciar>
        </tintervencao>
        <relacionados>
            <antecessor>
                <processo>
                    <url></url>
                    <nome></nome>
                </processo>
            </antecessor>
            <sintese>
                <processo>
                    <url></url>
                    <nome></nome>
                </processo>
            </sintese>
            <sintetizado>
                <processo>
                    <url></url>
                    <nome></nome>
                </processo>
            </sintetizado>
            <sucessor>
                <processo>
                    <url></url>
                    <nome></nome>
                </processo>
            </sucessor>
            <suplemento>
                <processo>
                    <url></url>
                    <nome></nome>
                </processo>
            </suplemento>
            <suplementop>
                <processo>
                    <url></url>
                    <nome></nome>
                </processo>
            </suplementop>
        </relacionados>
        <legislacao>
            <legis>
                <tipo></tipo>
                <artigo></artigo>
                <definicao></definicao>
            </legis>
        </legislacao>
    </contexto>
    <decisoes>
        <prazoca>
            <prazo></prazo>
            <forma></forma>
            <justificacao>
                <para>
                    <titulo></titulo>
                    <p></p>
                </para>
            </justificacao>
        </prazoca>
        <destinof>
            <destino></destino>
            <justificacao>
                <para>
                    <titulo></titulo>
                    <p></p>
                </para>
            </justificacao>
        </destinof>
    </decisoes>
</pn>
